### PR TITLE
Fix compilation/crash under MinGW.

### PR DESCRIPTION
**Pull request by rohit-n**

### CODE REVIEW

**Comment by DanielGibson** [comment]
So with this the game builds with MinGW and runs on Windows?

**Comment by DanielGibson** [comment]
(Ok, "runs" is a strong word for the current state, at least on Linux, but "starts and displays something that looks like the game and maybe even allows you to move a bit before it crashes" ;-))

**Comment by rohit-n** [comment]
Yes, it displays the SHODAN head, then the first level, where I can move with spacebar and the arrow keys.

**Comment by DanielGibson** [comment]
awesome!

**Pull request merged**
